@echo off
echo Освобождение порта 3000...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":3000" ^| find "LISTENING"') do (
    echo Остановка процесса %%a...
    taskkill /F /PID %%a
)
echo Запуск сервера разработки...
npm run dev
